openapi: 3.0.0
x-stoplight:
  id: 86rfvdj4j5ob6
info:
  title: niko
  version: '1.0'
  description: niko
  contact:
    name: yuuu
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/v1/nikos/{nikoId}':
    parameters:
      - schema:
          type: string
        name: nikoId
        in: path
        required: true
    get:
      summary: showNikos
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Niko'
        '404':
          description: User Not Found
      operationId: show-nikos
      description: show nikos
      tags:
        - nikos
    patch:
      summary: updateNikos
      operationId: update-nikos
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Niko'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: update nikos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Niko'
        description: Patch user properties to update.
      tags:
        - nikos
  /api/v1/nikos.json:
    post:
      summary: createNikos
      operationId: create-nikos
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Niko'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Niko'
        description: Post the necessary fields for the API to create a new user.
      description: create nikos
      tags:
        - nikos
    parameters: []
    get:
      summary: indexNikos
      operationId: index-nikos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Niko'
      tags:
        - nikos
      description: index nikos
components:
  schemas:
    Niko:
      title: Niko
      x-stoplight:
        id: b9w0i3pu7j0by
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
        mood:
          type: string
        date:
          type: string
        comment:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        user_id:
          type: integer
      required:
        - mood
        - date
  securitySchemes:
    uid:
      name: uid
      type: apiKey
      in: header
    client:
      name: client
      type: apiKey
      in: header
    access-token:
      name: access-token
      type: apiKey
      in: header
tags:
  - name: nikos
